### ISSUE TITLE
4. Criar com o RASA o arquivo `nlu.yml`

### ISSUE THREAD

**Issue by gustavohfelixs** [gustavohfelixs/barber-rasa-chat-bot#4]
Criar com o **RASA** o arquivo `nlu.yml` com todos os exemplos necessários de intenções para treinar o seu bot (**15 exemplos para cada intenção**). 

Na sequência copie e cole o conteúdo desse arquivo abaixo:

```
version: "3.1"

nlu:
  - lookup: dia_semana
    examples: |
      - segunda
      - terça
      - quarta
      - quinta
      - sexta
      - segunda-feira
      - terça-feira
      - quarta-feira
      - quinta-feira
      - sexta-feira
  - lookup: periodo_agendamento
    examples: |
      - manhã
      - tarde
  - regex: data_hora
    examples: |
      - \d{2}/\d{2}
      - \d{2}/\{2}/\{2,4}
  - intent: saudacao
    examples: |
      - Olá
      - Oi
      - Bom dia
      - Boa tarde
      - Boa noite
      - E aí
      - Salve
      - Posso te ajudar?
      - Preciso de um favor
      - Tenho uma pergunta
      - Boa noite, tudo bem?
      - Oi, tudo tranquilo?
      - Boa tarde, como vai?
      - E aí, beleza?
      - Salve, tudo certo?
      - Eai? Td bem?

  version: "3.1"

nlu:
  - intent: saudacao
    examples: |
      - Olá
      - Oi
      - Bom dia
      - Boa tarde
      - Boa noite
      - E aí
      - Salve
      - Posso te ajudar?
      - Preciso de um favor
      - Tenho uma pergunta
      - Boa noite, tudo bem?
      - Oi, tudo tranquilo?
      - Boa tarde, como vai?
      - E aí, beleza?
      - Salve, tudo certo?
      - Eai? Td bem?
      - Como está?
      - Opa, tudo bem?
      - Oi, como vai?

  - intent: agendamento
    examples: |
      - Gostaria de agendar um horário
      - Posso marcar um horário para hoje?
      - Tenho interesse em agendar um serviço
      - Gostaria de agendar um horário para amanhã
      - Quero agendar um horário para um corte
      - Tenho interesse em agendar um serviço para sábado
      - Gostaria de marcar um corte para a próxima [segunda](dia_semana)
      - Queria agendar um horário de manhã
      - Preciso marcar um corte para sexta-feira
      - Dá para marcar um horário para o fim de semana?
      - Consigo agendar para o próximo sábado?
      - Quero agendar um corte para amanhã
      - Pode marcar um horário para mim na terça-feira?
      - Tenho como agendar uma barba para quinta-feira?
      - Como faço para agendar um horário?

  - intent: agendamento_servico
    examples: |
      - Corte de [cabelo](servico)
      - Quero marcar um [corte](servico)
      - Corte de [cabelo e barba](servico)
      - [barba](servico)
      - [cabelo](servico)
      - Quero fazer [barba](servico) e [cabelo](servico)
      - Preciso agendar um [corte](servico)
      - Vou precisar de um corte de [cabelo](servico)
      - Preciso agendar para um [corte](servico)
      - Gostaria de marcar um [corte](servico)
      - Agendar para fazer a [barba](servico)
      - Tenho como fazer [cabelo](servico) e [barba](servico)?
      - Queria fazer só a [barba](servico)
      - Posso agendar só para [barba](servico)?
      - Queria marcar um [corte de cabelo](servico)

  - intent: agendamento_data_hora
    examples: |
      - Próxima [terça](dia_semana), pela [manhã](periodo_agendamento)
      - Na quinta-feira à tarde
      - segunda feira à tarde
      - No dia [27/10](data_hora) pela [manhã](periodo_agendamento)
      - 12/06 - manhã
      - 24/02, de manhã
      - Amanhã de manhã
      - Amanha a tarde
      - na quinta feira
      - Na quarta à noite
      - Amanhã no período da tarde
      - Próximo sábado de manhã
      - Pode ser na próxima segunda-feira à tarde?
      - Quero agendar para o dia 15 de outubro à tarde
      - Tem vaga amanhã pela manhã?

  - intent: agradecimento
    examples: |
      - Perfeito
      - Muito bom
      - Obrigado
      - valeu
      - vlw
      - agradeço a ajuda
      - Muito Obrigado pela ajuda
      - obg
      - você é top
      - top
      - agradeço
      - show de bola
      - massa
      - grato
      - Muito grato
      - Valeu pela atenção
      - Agradeço muito
      - Muitíssimo obrigado

  - intent: finalizacao
    examples: |
      - Não, é só isso!
      - não
      - só isso mesmo
      - Não, era apenas isso
      - não, tudo bem
      - Tudo certo
      - Não, por enquanto é isso mesmo
      - Somente isso
      - Não preciso de mais nada
      - Tudo bem!
      - Não, está tudo certo
      - Nada mais, obrigado
      - Por enquanto, é só isso
      - Tudo ok por aqui
      - Era só isso mesmo
      - Não, já resolvi

  - intent: endereco
    examples: |
      - Qual seu endereço?
      - Onde vocês estão localizados?
      - Onde é que vocês estão?
      - Onde é a barbearia?
      - Qual o endereço?
      - Me informe o endereço
      - Onde fica?
      - Me informe o local da barbearia
      - Qual local da barbearia?
      - Onde fica a barbearia?
      - Como faço para chegar na barbearia?
      - endereço
      - Qual o cep da barbearia?
      - Qual a rua da barbearia?
      - Onde é que fica?
      - Onde?
      - local
      - localização

  - intent: valores
    examples: |
      - Quanto é o corte de cabelo?
      - Quais os valores?
      - Quanto custa o corte de cabelo?
      - Qual preço da barba?
      - Qual preço do corte de cabelo?
      - Me informe valores
      - quanto é?
      - me diga o preço
      - poderia me dizer o preço
      - valores
      - valores serviços
      - me informe os preços
      - quanto está o corte?
      - quanto é a barba?
      - me diga o valor da barba
      - me informe o valor deste serviço?
      - quanto é o custo?
      - qual é o valor aqui?
      - qual o valor?
      - Pode me passar o preço?


```
