### ISSUE TITLE
05. Criar com o RASA o arquivo `stories.yml` e `rules.yml` 

### ISSUE THREAD

**Issue by gustavohfelixs** [gustavohfelixs/barber-rasa-chat-bot#5]
Criar com o **RASA** o arquivo `stories.yml `e `rules.yml` com todos os exemplos necessários para treinar o seu bot. Na sequência copie e cole o conteúdo desse arquivo abaixo (Seu bot deve conter ao menos 
**2 regras no rules.yml**:
```
stories.yml:
version: "3.1"

stories:
  - story: Agendamento de serviço
    steps:
      - intent: saudacao
      - action: utter_saudacao
      - intent: agendamento
      - action: utter_agendamento
      - intent: agendamento_servico
      - action: utter_agendamento_servico
      - intent: agendamento_data_hora
      - action: utter_agendamento_data_hora
      - intent: finalizacao
      - action: utter_finalizacao


rules.yml:
version: "3.1"

rules:

- rule: Agradecimento ao usuario
  steps:
  - intent: agradecimento
  - action: utter_agradecimento
- rule: Informa endereco
  steps:
  - intent: endereco
  - action: utter_endereco
- rule: Informa Valores
  steps: 
  - intent: valores
  - action: utter_valores
```
